version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "docbase-ranking-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uquaondzrb25"
s3_prefix = "docbase-ranking-stack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
